/**
 * Topic briefs for the blog agent.
 *
 * Every entry must have a slug, title and primaryKeyword that no existing
 * article uses -- the build validator enforces uniqueness across the whole
 * collection. `node scripts/blog/agent/check-topics.mjs` verifies that.
 *
 * `mustCover` is the editorial contract for the article: the agent hands it to
 * the model as required coverage, and it is what keeps 50 articles from
 * collapsing into the same generic outline.
 */

const SLOT_HOURS = ['09:00', '11:30', '14:00', '16:30', '19:00'];

// The collection's last existing article is 2026-08-30T18:30Z; this picks up the
// next morning and runs to 2026-09-09, keeping every date in the past.
const FIRST_DAY = Date.UTC(2026, 7, 31);

/** Five posts a day across ten days, starting 2026-08-31. */
function publishedAt(index) {
  const day = new Date(FIRST_DAY + Math.floor(index / SLOT_HOURS.length) * 86_400_000);
  const hour = SLOT_HOURS[index % SLOT_HOURS.length];
  return `${day.toISOString().slice(0, 10)}T${hour}:00Z`;
}

/** Shared coverage for the single-language "how to translate video to X" guides. */
function languageBrief({ language, region, script, traits }) {
  return {
    category: 'Translation Guides',
    audience: `A creator or localization owner deciding whether and how to publish their existing video library in ${language}`,
    angle: `A practical guide to producing ${language} audio and subtitles from existing video, focused on what actually goes wrong and how to check the output when you do not speak the language yourself.`,
    mustCover: [
      `who the ${language} audience is and where they are concentrated (${region})`,
      `the linguistic traits that affect dubbing and subtitling: ${traits}`,
      `how ${script} affects subtitle rendering, line length, fonts and reading speed`,
      'text expansion or contraction against the original timing, and what to do when a line no longer fits',
      'formality and register decisions the translation has to make, and how to specify them up front',
      'names, brand terms, units, numbers and dates that need a glossary before the first run',
      'voice selection and voice cloning for a recurring presenter, including consent and disclosure',
      'a concrete quality-review checklist a non-speaker can run, and how to brief a native reviewer',
      'a realistic first-project plan: which videos to start with and how to measure whether it worked',
    ],
  };
}

const DRAFTS = [
  // --- Language guides -----------------------------------------------------
  {
    slug: 'translate-video-to-slovenian',
    title: 'How to Translate Video to Slovenian: A Complete Production Guide',
    primaryKeyword: 'translate video to Slovenian',
    ...languageBrief({
      language: 'Slovenian',
      region: 'Slovenia and Slovenian-speaking communities in Italy, Austria and Hungary',
      script: 'the Latin alphabet with the carons c, s and z',
      traits: 'dual grammatical number, six cases, and free word order that changes emphasis',
    }),
  },
  {
    slug: 'translate-video-to-latvian',
    title: 'How to Translate Video to Latvian Without Losing Timing or Meaning',
    primaryKeyword: 'translate video to Latvian',
    ...languageBrief({
      language: 'Latvian',
      region: 'Latvia and the Latvian diaspora across Europe and North America',
      script: 'the Latin alphabet with macrons and cedillas',
      traits: 'seven noun cases, long and short vowel distinctions, and heavy inflection that lengthens lines',
    }),
  },
  {
    slug: 'translate-video-to-albanian',
    title: 'How to Translate Video to Albanian: Dialects, Timing, and Voice',
    primaryKeyword: 'translate video to Albanian',
    ...languageBrief({
      language: 'Albanian',
      region: 'Albania, Kosovo, North Macedonia, and diaspora communities in Italy, Germany and Switzerland',
      script: 'the Latin alphabet with digraphs such as dh, gj, ll, nj, rr, sh, th, xh and zh',
      traits: 'the Gheg and Tosk dialect split, definite noun endings, and an admirative mood with no direct English equivalent',
    }),
  },
  {
    slug: 'translate-video-to-macedonian',
    title: 'How to Translate Video to Macedonian: A Practical Localization Guide',
    primaryKeyword: 'translate video to Macedonian',
    ...languageBrief({
      language: 'Macedonian',
      region: 'North Macedonia and neighbouring Balkan markets',
      script: 'Cyrillic, with letters that differ from Serbian and Bulgarian Cyrillic',
      traits: 'postposed definite articles, three-way deixis, and close similarity to Bulgarian that invites mislabelled source audio',
    }),
  },
  {
    slug: 'translate-video-to-kazakh',
    title: 'How to Translate Video to Kazakh Across Cyrillic and Latin Script',
    primaryKeyword: 'translate video to Kazakh',
    ...languageBrief({
      language: 'Kazakh',
      region: 'Kazakhstan and Kazakh-speaking populations in China, Uzbekistan and Mongolia',
      script: 'both Cyrillic and the newer Latin orthography, which the audience may expect differently by age and region',
      traits: 'agglutinative suffix chains, vowel harmony, and frequent Russian code-switching in source audio',
    }),
  },
  {
    slug: 'translate-video-to-uzbek',
    title: 'How to Translate Video to Uzbek: Script, Register, and Delivery',
    primaryKeyword: 'translate video to Uzbek',
    ...languageBrief({
      language: 'Uzbek',
      region: 'Uzbekistan and Uzbek-speaking communities across Central Asia',
      script: 'the Latin orthography now standard in Uzbekistan alongside Cyrillic still common in older material',
      traits: 'agglutination, vowel harmony, and Russian loanwords whose pronunciation must be decided deliberately',
    }),
  },
  {
    slug: 'translate-video-to-azerbaijani',
    title: 'How to Translate Video to Azerbaijani: A Complete Workflow',
    primaryKeyword: 'translate video to Azerbaijani',
    ...languageBrief({
      language: 'Azerbaijani',
      region: 'Azerbaijan and the large Azerbaijani-speaking population of northwestern Iran',
      script: 'the Latin alphabet used in Azerbaijan and the Perso-Arabic script used in Iran',
      traits: 'agglutinative morphology, vowel harmony, and North versus South varietal differences in vocabulary',
    }),
  },
  {
    slug: 'translate-video-to-armenian',
    title: 'How to Translate Video to Armenian: Eastern, Western, and Both',
    primaryKeyword: 'translate video to Armenian',
    ...languageBrief({
      language: 'Armenian',
      region: 'Armenia plus a large diaspora in Russia, the United States, France and Lebanon',
      script: 'the Armenian alphabet, which needs font and line-length checks most subtitle tooling defaults get wrong',
      traits: 'the Eastern and Western Armenian split, which affects vocabulary, pronunciation and consonant voicing',
    }),
  },
  {
    slug: 'translate-video-to-sinhala',
    title: 'How to Translate Video to Sinhala: Subtitles, Voice, and Review',
    primaryKeyword: 'translate video to Sinhala',
    ...languageBrief({
      language: 'Sinhala',
      region: 'Sri Lanka, alongside a Tamil-speaking audience that often needs a parallel track',
      script: 'the Sinhala abugida, whose combining vowel signs and tall glyphs affect subtitle line height',
      traits: 'a strong split between literary and spoken registers that changes which one belongs in a dub',
    }),
  },
  {
    slug: 'translate-video-to-burmese',
    title: 'How to Translate Video to Burmese: Script, Timing, and Accessibility',
    primaryKeyword: 'translate video to Burmese',
    ...languageBrief({
      language: 'Burmese',
      region: 'Myanmar and Burmese-speaking communities in Thailand and beyond',
      script: 'the Burmese script, where Unicode versus legacy Zawgyi encoding still breaks subtitle files',
      traits: 'tone, minimal spacing between words, and politeness particles that carry social meaning',
    }),
  },
  {
    slug: 'translate-video-to-gujarati',
    title: 'How to Translate Video to Gujarati for Indian and Diaspora Audiences',
    primaryKeyword: 'translate video to Gujarati',
    ...languageBrief({
      language: 'Gujarati',
      region: 'Gujarat and a large diaspora in the United Kingdom, the United States and East Africa',
      script: 'the Gujarati abugida with combining marks and conjunct consonants',
      traits: 'honorific verb forms, English code-switching in urban speech, and diaspora vocabulary drift',
    }),
  },
  {
    slug: 'translate-video-to-afrikaans',
    title: 'How to Translate Video to Afrikaans: Register, Voice, and Reach',
    primaryKeyword: 'translate video to Afrikaans',
    ...languageBrief({
      language: 'Afrikaans',
      region: 'South Africa and Namibia, in a market where most viewers also understand English',
      script: 'the Latin alphabet with diacritics and the apostrophe-initial article',
      traits: 'double negation, compact compounding that shortens lines, and a wide formal-to-colloquial range',
    }),
  },
  {
    slug: 'translate-video-to-hausa',
    title: 'How to Translate Video to Hausa: Reaching West African Audiences',
    primaryKeyword: 'translate video to Hausa',
    ...languageBrief({
      language: 'Hausa',
      region: 'northern Nigeria, Niger, and a wide West African trade and broadcast region',
      script: 'the Boko Latin orthography with hooked letters, alongside Ajami in some contexts',
      traits: 'lexical tone, vowel length, and dialect differences between Kano and Sokoto varieties',
    }),
  },
  {
    slug: 'translate-video-to-igbo',
    title: 'How to Translate Video to Igbo Without Flattening Tone or Dialect',
    primaryKeyword: 'translate video to Igbo',
    ...languageBrief({
      language: 'Igbo',
      region: 'southeastern Nigeria and the Igbo diaspora',
      script: 'the Latin alphabet with dotted vowels and subscript marks that are often stripped by tooling',
      traits: 'lexical and grammatical tone, wide dialect variation, and a standard variety not everyone speaks natively',
    }),
  },
  {
    slug: 'translate-video-to-cantonese',
    title: 'How to Translate Video to Cantonese: Spoken Register and Written Chinese',
    primaryKeyword: 'translate video to Cantonese',
    ...languageBrief({
      language: 'Cantonese',
      region: 'Hong Kong, Macau, Guangdong, and Cantonese-speaking diaspora communities worldwide',
      script: 'Traditional Chinese characters, including written-Cantonese characters that do not appear in Standard Written Chinese',
      traits: 'six tones, the gap between spoken Cantonese and Standard Written Chinese, and heavy sentence-final particles',
    }),
  },
  {
    slug: 'translate-video-to-somali',
    title: 'How to Translate Video to Somali for Community and Public Service Media',
    primaryKeyword: 'translate video to Somali',
    ...languageBrief({
      language: 'Somali',
      region: 'Somalia, Somaliland, Djibouti, Ethiopia, Kenya and large resettled communities in Europe and North America',
      script: 'the Latin-based Somali orthography with doubled vowels marking length',
      traits: 'tone that distinguishes grammatical roles, vowel length, and dialect differences between Northern and Benaadir varieties',
    }),
  },

  // --- Platform and format -------------------------------------------------
  {
    slug: 'linkedin-video-translation',
    title: 'LinkedIn Video Translation: Reaching Professional Audiences in Their Language',
    primaryKeyword: 'LinkedIn video translation',
    category: 'Creator Growth',
    audience: 'A founder, marketer or subject-matter expert publishing video to LinkedIn who wants reach outside their home market',
    angle: 'How professional-network video differs from creator video, and how to localize it without sounding like a translated press release.',
    mustCover: [
      'why LinkedIn video is watched muted and what that means for subtitle-first localization',
      'the professional register problem: formality levels differ sharply by market',
      'square and vertical framing, and where burned-in captions can be safely placed',
      'whether to post one multilingual account or separate language pages, with trade-offs',
      'localizing the post copy, the first-line hook and the document carousel alongside the video',
      'job titles, credentials and company terms that must not be machine-translated',
      'using a cloned executive voice for dubbed thought-leadership, with consent and disclosure',
      'measuring what worked: dwell time, follower geography, inbound messages by market',
      'a repeatable weekly production loop for a small team',
    ],
  },
  {
    slug: 'facebook-video-translation',
    title: 'Facebook Video Translation: A Guide to Multilingual Reach on Meta Platforms',
    primaryKeyword: 'Facebook video translation',
    category: 'Creator Growth',
    audience: 'A page owner or community manager whose audience spans several language markets',
    angle: 'The practical mechanics of localizing Facebook video, including how the platform surfaces language and what that means for your publishing structure.',
    mustCover: [
      'uploading multiple caption tracks versus separate localized posts, and when each wins',
      'silent autoplay and why the first three seconds must work as text',
      'dialect targeting inside a single language, especially Spanish, Arabic and Portuguese',
      'community-language content where the source video itself is multilingual',
      'cross-posting a localized asset to Instagram and Reels without re-encoding damage',
      'comment moderation in languages the team does not read',
      'a language-selection method based on existing page insights rather than guesswork',
      'quality checks before a localized version goes live',
      'how to retire or update a localized version when the source changes',
    ],
  },
  {
    slug: 'app-store-video-localization',
    title: 'App Store Video Localization: Preview Videos That Convert in Every Market',
    primaryKeyword: 'app store video localization',
    category: 'Localization',
    audience: 'A mobile product marketer or growth lead responsible for store listings across countries',
    angle: 'App preview videos are short, silent-by-default, and store-reviewed. Localizing them is a different discipline from localizing marketing video.',
    mustCover: [
      'the constraints store previews impose: duration, capture requirements, device frames',
      'silent playback and the primacy of on-screen text over voice',
      'localizing the in-app UI shown in the capture, not just the caption track',
      'when a voiceover helps and when it is wasted effort',
      'keeping preview text consistent with the localized listing copy and screenshots',
      'right-to-left markets and mirrored layouts',
      'a review and re-capture workflow when the product UI changes',
      'measuring conversion by locale and deciding where to invest next',
      'common rejection and rework causes and how to avoid them',
    ],
  },
  {
    slug: 'product-launch-video-localization',
    title: 'Product Launch Video Localization: Shipping Every Language on Day One',
    primaryKeyword: 'product launch video localization',
    category: 'Enterprise',
    audience: 'A product marketing lead coordinating a simultaneous multi-market launch',
    angle: 'Launch video localization is a scheduling and embargo problem as much as a translation problem. This is how to run it backwards from the launch moment.',
    mustCover: [
      'building the localization schedule backwards from the embargo lift',
      'working from a locked cut versus a near-final cut, and the real cost of each',
      'pre-approving terminology, product names and claims before the video exists',
      'handling legal and regulatory review in markets with different claim rules',
      'confidentiality: who sees the asset, and how access is controlled before launch',
      'a contingency plan for a late edit that invalidates every localized track',
      'coordinating localized subtitles, dubbed audio, captions and social cutdowns as one release',
      'post-launch corrections without breaking existing embeds and links',
      'a reusable launch runbook a team can apply to the next release',
    ],
  },
  {
    slug: 'video-testimonial-translation',
    title: 'Video Testimonial Translation: Keeping Credibility Across Languages',
    primaryKeyword: 'video testimonial translation',
    category: 'Enterprise',
    audience: 'A customer marketing or advocacy manager localizing customer stories and case study video',
    angle: 'A testimonial works because a real person said it. Localization has to preserve that, which puts limits on how far you can adapt.',
    mustCover: [
      'consent that covers translation, dubbing and voice cloning, not just the original recording',
      'when to subtitle rather than dub, so the speaker is still audibly themselves',
      'accuracy obligations when a customer makes a factual or numeric claim',
      'handling spontaneous speech: hesitations, false starts, and how much to clean up',
      'preserving job titles, company names and industry terms across markets',
      'reviewing with the customer before publishing a localized version',
      'privacy and takedown handling when a customer relationship ends',
      'a workflow for producing many short localized cutdowns from one long interview',
      'measuring whether localized proof actually moves the markets it targets',
    ],
  },
  {
    slug: 'trade-show-video-localization',
    title: 'Trade Show Video Localization: Booth Content That Works Without Headphones',
    primaryKeyword: 'trade show video localization',
    category: 'Enterprise',
    audience: 'An events or field marketing manager preparing booth and stand content for international shows',
    angle: 'Booth video plays on a loop, in a loud hall, to people walking past. Localizing it well means designing for those conditions first.',
    mustCover: [
      'silent-first design: legible on-screen text and captions as the primary channel',
      'loop length, entry point and the fact that most viewers join mid-video',
      'which languages a specific show actually needs, based on attendee geography',
      'screen size, viewing distance, and minimum caption type size',
      'handheld and kiosk playback where audio is possible, and language selection at the device',
      'reusing the same source across several shows with different language sets',
      'file delivery, codecs and playback hardware constraints venues impose',
      'staff-facing localized material: demo scripts, one-pagers and follow-up video',
      'a pre-show checklist that catches broken localized assets before shipping',
    ],
  },
  {
    slug: 'localizing-video-metadata',
    title: 'Localizing Video Metadata: Titles, Descriptions, Chapters, and Tags',
    primaryKeyword: 'video metadata localization',
    category: 'Creator Growth',
    audience: 'A channel manager or content operations lead publishing the same video across markets',
    angle: 'Most teams localize the video and stop. The metadata is what decides whether anyone in that market ever sees it.',
    mustCover: [
      'why a literally translated title usually loses to a market-native one',
      'keyword research in the target language rather than translating your English keywords',
      'chapter markers, and how translated chapters change perceived length and navigation',
      'description structure: the first two lines, links, and calls to action per market',
      'tags, hashtags and category conventions that differ by platform and country',
      'thumbnail text localization and character-count limits',
      'keeping metadata versions in sync when the source video is updated',
      'a spreadsheet-or-database structure for tracking metadata across many locales',
      'measuring impressions and click-through by locale to find where metadata is the bottleneck',
    ],
  },

  // --- Content types -------------------------------------------------------
  {
    slug: 'audiobook-localization-guide',
    title: 'Audiobook Localization: Producing Multilingual Editions With AI Narration',
    primaryKeyword: 'audiobook localization',
    category: 'Voice AI',
    audience: 'An independent author or small publisher considering multilingual audio editions',
    angle: 'Audiobook localization has stricter continuity demands than video. This covers what changes when a listener spends nine hours with one voice.',
    mustCover: [
      'why long-form listening exposes flaws that a three-minute sample hides',
      'narrator identity, voice cloning with author consent, and disclosure to listeners',
      'chapter-level workflow, file structure and retail platform requirements',
      'pronunciation consistency for character names, invented terms and place names across an entire book',
      'pacing, paragraph breaks and how to control breath and pause in generated narration',
      'dialogue and multi-character narration, and whether to differentiate voices',
      'translation quality for literary text versus non-fiction, and where each needs a human pass',
      'a proofing method: which chapters to listen to in full and which to spot check',
      'a realistic cost and time comparison against studio production, described qualitatively',
    ],
  },
  {
    slug: 'explainer-animation-localization',
    title: 'Explainer Video Localization: Animation, Voiceover, and On-Screen Text',
    primaryKeyword: 'explainer video localization',
    category: 'Localization',
    audience: 'A marketer or agency producer localizing animated explainer and motion graphics content',
    angle: 'Animation is timed to a script. Change the language and the timing breaks. This is how to design and localize explainers so that does not happen.',
    mustCover: [
      'designing the original explainer for localization: text space, timing headroom, layered projects',
      'text expansion in German, Finnish and Russian against fixed animation timing',
      'whether to re-render motion graphics per language or overlay localized text',
      'voiceover pacing against animation beats, and how to adjust one without ruining the other',
      'localizing charts, currency, icons, gestures and culturally loaded imagery',
      'right-to-left layouts and mirrored motion',
      'source file hygiene: fonts, editable text layers and version control',
      'a review pass that checks sync between voice, animation and on-screen text',
      'a cost-efficient approach for a library of explainers rather than a single video',
    ],
  },
  {
    slug: 'recorded-meeting-translation',
    title: 'Recorded Meeting Translation: Making Internal Video Useful Across Languages',
    primaryKeyword: 'recorded meeting translation',
    category: 'Enterprise',
    audience: 'An internal communications or operations lead at a company with distributed, multilingual teams',
    angle: 'Recorded meetings are the largest untapped video library most companies own. Translating them well is mostly a triage and governance problem.',
    mustCover: [
      'triage: which recordings are worth translating and which should simply expire',
      'poor source audio from conference rooms and laptop microphones, and what improves it',
      'overlapping speech, crosstalk and diarization limits in real meetings',
      'transcript-first delivery versus dubbed audio, and which one people actually use',
      'confidentiality classification and access control for translated internal media',
      'retention policies and the risk of translating something that should have been deleted',
      'names, internal acronyms and project codenames that need a shared glossary',
      'making translated recordings searchable so they get used more than once',
      'a lightweight approval process that does not block routine internal sharing',
    ],
  },
  {
    slug: 'user-generated-content-translation',
    title: 'User-Generated Content Translation: Scale, Consent, and Quality Control',
    primaryKeyword: 'user-generated content translation',
    category: 'Creator Growth',
    audience: 'A community or brand manager who wants to reuse customer and community video across markets',
    angle: 'UGC is high-volume, uneven in quality, and belongs to someone else. Each of those changes how you translate it.',
    mustCover: [
      'rights and consent: what permission to translate and dub actually requires',
      'variable source quality and an intake standard that filters what is worth processing',
      'slang, humour, regional references and the limits of literal translation',
      'moderation before and after translation, including what a translation can accidentally amplify',
      'attribution and credit when a piece is republished in another language',
      'batch workflows for many short clips rather than one long asset',
      'whether to dub UGC at all, versus subtitling to keep the creator audible',
      'measuring performance without punishing creators whose clips are used in weaker markets',
      'a simple policy document a community team can operate from',
    ],
  },
  {
    slug: 'audio-drama-localization',
    title: 'Audio Drama Localization: Multi-Voice Fiction in New Languages',
    primaryKeyword: 'audio drama localization',
    category: 'Voice AI',
    audience: 'A fiction podcast or audio drama producer considering translated editions',
    angle: 'Scripted multi-voice audio has no picture to carry meaning. Everything depends on voice distinctness, performance and sound design.',
    mustCover: [
      'casting a target-language voice map and keeping it stable across an entire season',
      'making characters distinguishable by voice alone when the listener has no visual cue',
      'emotional performance, and how to direct generated speech toward it',
      'preserving sound design, music and effects while replacing dialogue',
      'scripts with wordplay, accents or dialect as a plot device, and how to adapt them',
      'episode continuity: recurring phrases, catchphrases and character names',
      'release strategy for translated seasons, including whether to launch simultaneously',
      'a listening-review protocol that catches voice drift between episodes',
      'rights and credits for writers, performers and translators',
    ],
  },
  {
    slug: 'vr-360-video-localization',
    title: '360 Video Localization: Subtitles and Audio for Immersive Content',
    primaryKeyword: '360 video localization',
    category: 'Technical Guides',
    audience: 'An immersive media producer or XR developer localizing 360 and VR video experiences',
    angle: 'In a headset the viewer chooses where to look. Subtitles and dialogue have to work in a space, not on a rectangle.',
    mustCover: [
      'why flat subtitle placement fails in a 360 field of view',
      'head-locked versus world-locked subtitle placement and the comfort trade-offs',
      'directing attention to an off-view speaker without breaking immersion',
      'spatial and ambisonic audio, and what happens to it when dialogue is replaced',
      'comfort, motion sickness and reading load in headsets',
      'accessibility for immersive media, including captions for non-speech sound',
      'file formats, projection types and metadata that survive a localization round trip',
      'testing in-headset rather than on a monitor, and what that testing must cover',
      'a scoped starting project for a team new to immersive localization',
    ],
  },
  {
    slug: 'esports-broadcast-localization',
    title: 'Esports Broadcast Localization: Casting, Clips, and Multilingual Streams',
    primaryKeyword: 'esports broadcast localization',
    category: 'Localization',
    audience: 'A tournament organizer or esports media team serving international viewers',
    angle: 'Esports audiences are global by default. The hard part is game terminology, speed of speech, and the split between live and post-event content.',
    mustCover: [
      'live multilingual casting versus post-event localized VOD and clips',
      'game-specific terminology, ability names and community jargon that must not be translated literally',
      'extremely fast play-by-play speech and its effect on subtitle reading speed',
      'on-screen overlays, scoreboards and HUD text in localized versions',
      'clipping and vertical cutdowns for social, at high volume and short turnaround',
      'community-preferred wording, including terms fans keep in English',
      'a glossary process that involves casters and community moderators',
      'rights, publisher requirements and regional distribution constraints',
      'measuring which language markets justify a dedicated stream next season',
    ],
  },
  {
    slug: 'beauty-and-fashion-video-translation',
    title: 'Beauty and Fashion Video Translation: Product Names, Claims, and Tone',
    primaryKeyword: 'beauty video translation',
    category: 'Creator Growth',
    audience: 'A beauty or fashion creator, or a brand social team, expanding into new language markets',
    angle: 'This category is dense with product names, ingredient terms and regulated claims. Translating it casually creates both confusion and legal risk.',
    mustCover: [
      'product and shade names that stay in the source language, and how to mark them',
      'ingredient terminology and INCI names across markets',
      'regulated claims and how they differ by region, described in general terms rather than as legal advice',
      'tone and intimacy: the conversational register that makes this content work',
      'sizing, measurement and price conventions when they appear on screen',
      'creator voice preservation through voice cloning, and disclosure to the audience',
      'shoppable links, affiliate disclosures and localized calls to action',
      'a per-video checklist covering names, claims and on-screen text',
      'sequencing market entry so review effort stays manageable',
    ],
  },
  {
    slug: 'diy-tutorial-video-translation',
    title: 'DIY Video Translation: Tools, Measurements, and Safety Across Markets',
    primaryKeyword: 'DIY video translation',
    category: 'Creator Growth',
    audience: 'A how-to, home improvement or maker creator localizing an instructional back catalogue',
    angle: 'Instructional video has a correctness requirement. A mistranslated measurement or tool name is not a style problem, it is a wrong result or an injury.',
    mustCover: [
      'imperial and metric conversion, and whether to convert on screen, in voice, or both',
      'tool, fastener and material names that differ between markets even in the same language',
      'standards and voltages that make a step wrong or unsafe in another country',
      'safety warnings and how to keep them prominent after translation',
      'demonstrations where the voice describes something happening on screen, and timing pressure',
      'text overlays showing quantities, temperatures and cut lists',
      'a review pass by someone who has actually done the task in that market',
      'batch-localizing a long back catalogue in priority order',
      'handling comments and corrections from viewers in languages the creator does not speak',
    ],
  },

  // --- Industry ------------------------------------------------------------
  {
    slug: 'clinical-trial-video-translation',
    title: 'Clinical Trial Video Translation: Consent, Accuracy, and Audit Trails',
    primaryKeyword: 'clinical trial video translation',
    category: 'Enterprise',
    audience: 'A clinical operations or regulatory affairs professional handling multilingual trial materials',
    angle: 'Trial video sits inside a regulated, auditable process. This covers the controls that have to exist around translation, without offering regulatory advice.',
    mustCover: [
      'the categories of trial video: participant recruitment, informed consent, training, and patient instruction',
      'plain-language requirements and reading level, and why they survive translation only if planned',
      'terminology control for medical terms, dosages and device names',
      'the need for documented review, approval and version history',
      'audit trails and being able to show what changed, when, and who approved it',
      'data protection for recordings containing participant information',
      'accessibility obligations that run in parallel with translation',
      'a clear statement that qualified regulatory and linguistic review is required and that this article is not a substitute',
      'a practical intake checklist before any trial video enters a localization workflow',
    ],
  },
  {
    slug: 'in-flight-entertainment-localization',
    title: 'In-Flight Entertainment Localization: Subtitles, Dubs, and Delivery Specs',
    primaryKeyword: 'in-flight entertainment localization',
    category: 'Enterprise',
    audience: 'A content operations manager working with airline and IFE content service providers',
    angle: 'IFE has unusual constraints: fixed hardware, strict delivery specs, editing for suitability, and route-driven language sets.',
    mustCover: [
      'route-driven language selection rather than global language strategy',
      'delivery specifications, file formats and metadata that IFE systems require',
      'seat-back screen size and viewing distance versus subtitle type size',
      'content editing for suitability and how edits ripple into every localized track',
      'audio delivery over passenger headphones and loudness normalization',
      'multiple audio tracks and language selection in the seat-back interface',
      'accessibility features including closed captions and audio description',
      'cycle planning: monthly content refreshes and lead times',
      'quality checks specific to the playback hardware rather than a desktop preview',
    ],
  },
  {
    slug: 'public-transit-announcement-translation',
    title: 'Transit Announcement Translation: Multilingual Audio and Screens That Work',
    primaryKeyword: 'transit announcement translation',
    category: 'Accessibility',
    audience: 'A public transit communications or accessibility lead responsible for rider information',
    angle: 'Transit information is safety information delivered in noise, under time pressure, to people who may be anxious or unfamiliar. That shapes every localization choice.',
    mustCover: [
      'the difference between routine, service-disruption and emergency announcements',
      'station and stop names: transliteration, pronunciation and when never to translate',
      'noise, reverberation and intelligibility in stations and vehicles',
      'how many languages an announcement can carry before it becomes useless',
      'screen text paired with audio, and synchronizing the two',
      'accessibility for riders who are deaf, hard of hearing, blind or have low vision',
      'consistent voice identity across a network, including cloned voice for a recognizable system voice',
      'a pre-recorded library versus generated announcements for dynamic information',
      'a testing protocol that includes listening on site rather than in an office',
    ],
  },
  {
    slug: 'developer-tutorial-localization',
    title: 'Developer Tutorial Localization: Code, Commands, and Technical Terms',
    primaryKeyword: 'developer tutorial localization',
    category: 'Developer Guides',
    audience: 'A developer relations or technical documentation lead localizing video tutorials and course content',
    angle: 'Developer video is full of things that must not be translated. Getting the boundary right between prose and code is most of the work.',
    mustCover: [
      'what never gets translated: code, identifiers, CLI commands, error strings, file paths',
      'terms the local developer community keeps in English, and how to discover them',
      'screen recordings of an English IDE or console, and whether to re-record',
      'reading code aloud in another language, including how symbols and operators are spoken',
      'keeping tutorials in sync with a fast-moving API or SDK across every localized version',
      'subtitle line length when a code identifier consumes half the line',
      'a glossary that developer-community reviewers actually maintain',
      'pairing localized video with localized written docs so search works',
      'deciding which languages a developer audience genuinely needs',
    ],
  },
  {
    slug: 'customer-onboarding-video-localization',
    title: 'Customer Onboarding Video Localization: Faster Activation in Every Market',
    primaryKeyword: 'customer onboarding video localization',
    category: 'Enterprise',
    audience: 'A customer success or lifecycle marketing lead responsible for activation across regions',
    angle: 'Onboarding video is measured, not admired. Localizing it is an activation-rate exercise with a clear feedback loop.',
    mustCover: [
      'mapping the onboarding journey and identifying which steps actually need video',
      'product UI shown in the video versus the localized UI the customer sees',
      'keeping in-product terminology identical between the app and the video',
      'short modular videos versus one long walkthrough, and which localizes better',
      'in-app placement, help centre embedding and email sequences per locale',
      'updating localized onboarding when the product changes, without a full re-record',
      'measuring activation, time-to-value and support ticket deflection by language',
      'a prioritization method for which markets to localize first',
      'a maintenance owner and review cadence so the library does not rot',
    ],
  },
  {
    slug: 'hospitality-staff-training-translation',
    title: 'Hospitality Training Video Translation: Frontline Teams, Many Languages',
    primaryKeyword: 'hospitality training video translation',
    category: 'Enterprise',
    audience: 'A learning and development or operations manager in hotels, restaurants or venues',
    angle: 'Hospitality workforces are multilingual, high-turnover and often mobile-only. Training localization has to fit those conditions or it does not get watched.',
    mustCover: [
      'the language profile of a frontline workforce, which rarely matches the guest language profile',
      'mobile-first, short-form delivery on personal devices',
      'service standards, scripts and phrases staff must say to guests, in the guest language',
      'food safety, allergen and hygiene content where accuracy is not negotiable',
      'demonstrations where the voice tracks a physical action on screen',
      'literacy variation and why audio plus visuals beats text-heavy modules',
      'compliance record keeping across languages',
      'seasonal hiring peaks and localization lead time',
      'measuring completion and comprehension rather than just distribution',
    ],
  },

  // --- Craft and technical -------------------------------------------------
  {
    slug: 'pronunciation-dictionaries-for-dubbing',
    title: 'Pronunciation Dictionaries for Dubbing: Getting Names and Terms Right',
    primaryKeyword: 'pronunciation dictionary for dubbing',
    category: 'Technical Guides',
    audience: 'A localization engineer or producer responsible for output quality across many episodes',
    angle: 'A pronunciation dictionary is the highest-leverage artefact in a dubbing pipeline. This is how to build, test and maintain one.',
    mustCover: [
      'what belongs in a pronunciation dictionary: brand names, people, places, acronyms, product terms, numbers',
      'phonetic notation options and plain respelling, and the trade-off between precision and maintainability',
      'per-language entries, because one name is not pronounced identically in every target',
      'acronyms that are spelled out in one language and read as a word in another',
      'conflict resolution when a term is also an ordinary word',
      'testing entries with short generated samples before applying them to a full render',
      'ownership, review and change control as the dictionary grows',
      'integrating the dictionary into a batch pipeline so every job inherits it',
      'a starter template a team can populate in an afternoon',
    ],
  },
  {
    slug: 'numbers-dates-units-in-subtitles',
    title: 'Numbers, Dates, and Units in Subtitles: Localization Details That Break Trust',
    primaryKeyword: 'number and date localization in subtitles',
    category: 'Technical Guides',
    audience: 'A subtitle editor, localization QA reviewer or content operations lead',
    angle: 'Numeric formatting errors are small, frequent and disproportionately damaging to credibility. This is a systematic treatment of them.',
    mustCover: [
      'decimal separators and digit grouping, and how they invert between markets',
      'date order and month names, including where an ambiguous date is genuinely dangerous',
      'twelve and twenty-four hour clocks, and time zones spoken aloud',
      'currency: symbol placement, conversion, and when not to convert',
      'measurement units, and when a converted figure needs rounding rather than precision',
      'large-number naming systems, including lakh and crore',
      'numerals in scripts that use their own digit forms',
      'percentages, ranges, ratios and how they are read aloud in a dub',
      'a QA rule set and spot-check method a reviewer can apply consistently',
    ],
  },
  {
    slug: 'profanity-and-sensitive-content-in-dubbing',
    title: 'Profanity and Sensitive Content in Dubbing: Policy, Register, and Judgment',
    primaryKeyword: 'profanity in dubbing',
    category: 'Localization',
    audience: 'A localization manager setting policy for content with strong language or difficult subject matter',
    angle: 'Strength of language does not map one-to-one between languages. Teams need an explicit policy rather than a per-episode argument.',
    mustCover: [
      'why a literal translation of profanity is usually either too strong or too weak',
      'writing an explicit policy: preserve, soften, or adapt, decided before production',
      'platform and broadcaster standards, and age rating implications',
      'religious, political and culturally sensitive references that carry different weight by market',
      'slurs and hate speech, and why these require named human decision-makers',
      'documentary and journalistic content where accuracy of the record matters',
      'subtitle versus dub divergence, and whether the two tracks may differ',
      'content warnings and metadata that travel with a localized version',
      'an escalation path for cases a reviewer should not decide alone',
    ],
  },
  {
    slug: 'code-switching-in-video-translation',
    title: 'Code-Switching in Video Translation: When Speakers Mix Languages',
    primaryKeyword: 'code-switching in video translation',
    category: 'Technical Guides',
    audience: 'A localization engineer or producer handling multilingual source audio',
    angle: 'Most pipelines assume one source language. Real speakers switch mid-sentence, and that assumption is where the output quietly fails.',
    mustCover: [
      'how single-language ASR assumptions produce garbled transcripts on mixed speech',
      'common patterns: Hinglish, Spanglish, Taglish, Arabic-French, Swahili-English',
      'intra-sentence switching versus speaker-level switching, and why they need different handling',
      'deciding what the switch means: is the English word the term, or just habit',
      'subtitle conventions for marking a second language on screen',
      'dubbing decisions: preserve the switch, normalize to one language, or flag for a human',
      'segmentation and timing problems introduced by mixed-language audio',
      'building test clips that represent the real speech in your library',
      'a review workflow that routes ambiguous switches to a bilingual reviewer',
    ],
  },
  {
    slug: 'on-screen-text-localization',
    title: 'On-Screen Text Localization: Titles, Lower Thirds, and Burned-In Graphics',
    primaryKeyword: 'on-screen text localization',
    category: 'Localization',
    audience: 'A video editor or localization producer dealing with graphics baked into a finished video',
    angle: 'The audio is only half the video. On-screen text is where localization projects run over budget, and it is almost always avoidable upstream.',
    mustCover: [
      'the difference between text you can replace and text burned into the picture',
      'planning for localization at edit time: separate graphics layers, safe areas, extra timing',
      'text expansion and what a longer German or Russian string does to a fixed lower third',
      'font coverage for target scripts, and fallback fonts that silently ruin a design',
      'right-to-left layouts, mirrored graphics and directional icons',
      'when to overlay a translated caption instead of re-rendering the graphic',
      'collision between burned-in text and subtitles, and how to reposition',
      'a triage method for a back catalogue where source project files are gone',
      'a handover spec that stops the problem recurring on the next production',
    ],
  },
  {
    slug: 'subtitle-positioning-and-overlap',
    title: 'Subtitle Positioning: Avoiding Overlap With Graphics, Faces, and Captions',
    primaryKeyword: 'subtitle positioning',
    category: 'Accessibility',
    audience: 'A subtitle editor or accessibility reviewer working across platforms and aspect ratios',
    angle: 'Subtitle placement is treated as a default setting. Treated as a design decision instead, it fixes a large share of readability complaints.',
    mustCover: [
      'default bottom-centre placement and the specific cases where it fails',
      'moving subtitles to avoid burned-in text, speaker faces and important action',
      'platform UI chrome that covers the lower third on mobile and in feeds',
      'vertical, square and cinematic aspect ratios, and safe zones for each',
      'line breaking, line count and how they interact with placement',
      'speaker identification and positioning in multi-speaker scenes',
      'contrast, background boxes and outlines for legibility over varied footage',
      'format support: what SRT cannot express and what VTT and ASS can',
      'a review pass on the actual target device rather than an editing timeline',
    ],
  },
  {
    slug: 'audio-ducking-for-dubbed-video',
    title: 'Audio Ducking in Dubbing: Balancing Voice, Music, and Effects',
    primaryKeyword: 'audio ducking in dubbing',
    category: 'Technical Guides',
    audience: 'An audio editor or localization producer responsible for the final mix of dubbed video',
    angle: 'A technically correct dub can still sound wrong because the new voice does not sit in the original soundscape. Ducking and mix balance are how that gets fixed.',
    mustCover: [
      'what ducking is and why a dubbed voice needs different treatment than original dialogue',
      'static ducking versus dynamic, envelope-following ducking',
      'attack and release timing, and the audible artefacts of getting them wrong',
      'working from separated dialogue, music and effects stems versus a mixed track',
      'residual original dialogue bleeding under the new voice, and how to catch it',
      'preserving music intent when a lyric or a musical moment collides with speech',
      'loudness targets and how ducking interacts with final normalization',
      'checking the mix on phone speakers, headphones and television',
      'a repeatable mix checklist for a dubbing pipeline',
    ],
  },
  {
    slug: 'voice-casting-brief-for-dubbing',
    title: 'Writing a Voice Casting Brief for Dubbing: Getting the Right Voice First Time',
    primaryKeyword: 'voice casting brief',
    category: 'Voice AI',
    audience: 'A localization producer or brand owner selecting voices for a multi-language dubbing project',
    angle: 'Most voice dissatisfaction traces back to a brief that was never written. This is the document that prevents it.',
    mustCover: [
      'what a casting brief contains: role, audience, register, age range, energy, pace, warmth',
      'describing voice qualities in words a reviewer in another language can actually apply',
      'brand voice consistency across languages when the target voices are all different people',
      'reference clips and how to use them without asking for an impersonation',
      'when to clone a specific speaker instead of casting, with consent and disclosure',
      'multi-speaker content and building a voice map that stays stable across episodes',
      'shortlisting and comparing candidates on the same test lines',
      'documenting the final decision so later episodes inherit it',
      'a reusable brief template with the fields that matter',
    ],
  },
  {
    slug: 'localized-thumbnail-and-title-testing',
    title: 'Localized Thumbnail and Title Testing: Finding What Works Per Market',
    primaryKeyword: 'localized thumbnail testing',
    category: 'Creator Growth',
    audience: 'A channel or growth manager running video across multiple language markets',
    angle: 'A translated thumbnail is not a localized one. Testing is the only way to find out which is which, and most teams test wrong.',
    mustCover: [
      'why thumbnail conventions differ by market and platform',
      'text length on thumbnails after translation, and scripts that need larger type',
      'faces, gestures, colours and symbols that read differently across cultures',
      'designing a test that measures click-through rather than opinion',
      'sample size and how long a test needs to run before it means anything',
      'confounds: publishing time, audience size and algorithmic variance by market',
      'testing titles and thumbnails together versus separately',
      'recording results so the team builds market-specific knowledge over time',
      'when to stop testing and standardize on a template',
    ],
  },
  {
    slug: 'handling-overlapping-dialogue-in-dubbing',
    title: 'Overlapping Dialogue in Dubbing: Crosstalk, Interruptions, and Panels',
    primaryKeyword: 'overlapping dialogue in dubbing',
    category: 'AI Dubbing',
    audience: 'A dubbing producer or editor working with unscripted, conversational source material',
    angle: 'Scripted dialogue takes turns. Real conversation does not, and overlap is where automated dubbing degrades fastest.',
    mustCover: [
      'why overlapping speech breaks transcription, diarization and timing at once',
      'types of overlap: backchannels, interruptions, simultaneous starts, sustained crosstalk',
      'which overlaps carry meaning and which can be dropped without loss',
      'strategies: stagger, prioritize a speaker, compress, or leave original audio underneath',
      'subtitle handling of overlap, which has different conventions from audio',
      'panel discussions, debates and roundtables specifically',
      'source capture choices that prevent the problem, including per-speaker microphones',
      'a review method that finds overlap failures quickly in a long recording',
      'setting expectations with stakeholders about what unscripted material can achieve',
    ],
  },
  {
    slug: 'silence-and-pacing-in-dubbed-video',
    title: 'Pacing in Dubbed Video: Why Silence Matters as Much as Speech',
    primaryKeyword: 'pacing in dubbed video',
    category: 'AI Dubbing',
    audience: 'A dubbing editor or reviewer trying to explain why a technically accurate dub still feels wrong',
    angle: 'Generated speech tends to fill every gap. The pauses in the original are information, and preserving them is a specific, learnable craft.',
    mustCover: [
      'what pauses do: emphasis, comprehension time, emotional beat, turn-taking, breath',
      'the failure mode where a dub is accurate but relentless',
      'timing pressure from text expansion, and why speeding speech is the wrong first fix',
      'script adaptation to shorten a line rather than compress the audio',
      'breath, filler and disfluency, and how much to preserve',
      'scene changes, cuts and visual beats that dictate where speech cannot start',
      'instructional content where the viewer needs time to look at the screen',
      'how to review pacing: what to listen for and how to describe the problem precisely',
      'a set of adjustments an editor can apply in order of least damage',
    ],
  },
  {
    slug: 'dubbing-quality-sampling-plan',
    title: 'Dubbing Quality Sampling: Reviewing Large Volumes Without Watching Everything',
    primaryKeyword: 'dubbing quality sampling',
    category: 'Enterprise',
    audience: 'A localization quality lead responsible for many hours of output across many languages',
    angle: 'Full review does not scale past a certain volume. A defensible sampling plan is what replaces it, and most teams improvise one badly.',
    mustCover: [
      'why full review fails at scale and what it costs to pretend otherwise',
      'risk-weighting content: regulated, public-facing, high-traffic and evergreen first',
      'designing a sample: how much, from where in each asset, and chosen how',
      'targeted sampling of known weak points rather than uniformly random minutes',
      'a severity scale that distinguishes a wrong fact from an awkward phrase',
      'acceptance thresholds and what happens when a sample fails',
      'reviewer calibration so two people score the same clip the same way',
      'feeding findings back into glossaries, prompts and pronunciation dictionaries',
      'reporting that a non-specialist stakeholder can act on',
    ],
  },
];

export const TOPICS = DRAFTS.map((topic, index) => ({ ...topic, publishedAt: publishedAt(index) }));
